
set(CMAKE_SYSTEM_NAME Linux)

set(BREW $ENV{BREW})
set(TARGET_TRIPLE x86_64-unknown-linux-elf)
set(TOOLCHAIN_ROOT ${BREW}/toolchain/${TARGET_TRIPLE}/)

set(CMAKE_SYSROOT ${TOOLCHAIN_ROOT}/sysroot/)
set(CLANG_PREFIX_PATH_OPTION -B${TOOLCHAIN_ROOT}/bin/)

set(CMAKE_C_COMPILER          $ENV{CC} ${CLANG_PREFIX_PATH_OPTION})
set(CMAKE_C_COMPILER_TARGET   ${TARGET_TRIPLE})
set(CMAKE_CXX_COMPILER        $ENV{CXX} ${CLANG_PREFIX_PATH_OPTION})
set(CMAKE_CXX_COMPILER_TARGET ${TARGET_TRIPLE})

set(CMAKE_AR ${TOOLCHAIN_ROOT}/bin/ar CACHE INTERNAL "CMAKE_AR" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})

# include_directories(${CMAKE_SYSROOT}/usr/include/c++/v1/)

# set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -v -Wl,--verbose" CACHE INTERNAL "CMAKE_C_FLAGS" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fcolor-diagnostics" CACHE INTERNAL "CMAKE_CXX_FLAGS" FORCE)
