
set(CMAKE_SYSTEM_NAME Linux)

set(WR_ROOT $ENV{WR_ROOT}/)
set(WR_TOOLCHAIN_ROOT ${WR_ROOT}/common_pc-glibc_std/)
set(WR_KERNEL std)
set(WR_ARCH i686)
set(TARGET_TRIPLE i586-wrs-linux-gnu)

set(HOST_CROSS ${WR_TOOLCHAIN_ROOT}/x86-linux2)
set(PLATFORM Cabinet CACHE INTERNAL "PLATFORM" FORCE )
set(BUILD_SYS_VERSION VENUS
    CACHE INTERNAL "BUILD_SYS_VERSION"
    FORCE)

set(CMAKE_SYSROOT ${WR_TOOLCHAIN_ROOT}/sysroot/)
set(CMAKE_INSTALL_PREFIX ${CMAKE_SYSROOT} CACHE INTERNAL "CMAKE_INSTALL_PREFIX"  FORCE)
set(CMAKE_SYSTEM_PROCESSOR ${WR_ARCH})

set(CLANG_PREFIX_PATH_OPTION -B${WR_TOOLCHAIN_ROOT}/${TARGET_TRIPLE}/)

set(CMAKE_C_COMPILER          /usr/bin/clang ${CLANG_PREFIX_PATH_OPTION})
set(CMAKE_C_COMPILER_TARGET   ${TARGET_TRIPLE})
set(CMAKE_CXX_COMPILER        /usr/bin/clang++ ${CLANG_PREFIX_PATH_OPTION})
set(CMAKE_CXX_COMPILER_TARGET ${TARGET_TRIPLE})

set(HOST_CROSS   ${WR_TOOLCHAIN_ROOT}/x86-linux2)
set(CMAKE_STRIP  ${HOST_CROSS}/${TARGET_TRIPLE}-${WR_ARCH}-glibc_${WR_KERNEL}-strip CACHE INTERNAL "CMAKE_STRIP"  FORCE)
set(CMAKE_LINKER ${HOST_CROSS}/${TARGET_TRIPLE}-${WR_ARCH}-glibc_${WR_KERNEL}-ld    CACHE INTERNAL "CMAKE_LINKER" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})

include_directories(${CMAKE_SYSROOT}/usr/include/c++/v1/)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -stdlib=libc++ -ferror-limit=5 -fcolor-diagnostics -fomit-frame-pointer -pipe -Wall -Wextra -Wpointer-arith -g -O3" CACHE INTERNAL "CMAKE_CXX_FLAGS" FORCE)
